# Copyright 2026 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

minimum_pre_commit_version: "2.9.0"
ci:
  autoupdate_schedule: monthly
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: forbid-symlinks
        name: Forbid symlinks
        entry: Forbid symlinks
        language: fail
        types: [symlink]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.7
    hooks:
      - id: uv-lock
  - repo: https://github.com/google/addlicense
    rev: "v1.2.0"
    hooks:
      - id: addlicense
        args: ["-s=only", -l, "MIT", -c, "Lincoln Institute of Land Policy"]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
      - id: pyright
