# Copyright 2026 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

name: Prek checks

on: [push, pull_request]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: uv sync dependencies
        run: uv sync --all-extras
      - name: Run prek
        uses: j178/prek-action@v2
